vich_uploader:
    db_driver: orm

    mappings:
       partner_image:
           uri_prefix: /images/partners
           upload_destination: '%kernel.project_dir%/public/images/partners'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
           
    metadata:
        type: attribute