vich_uploader:
    db_driver: orm

    mappings:
        event_image:
            uri_prefix: /uploads/event
            upload_destination: "%kernel.project_dir%/public/uploads/event"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute
